services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"   # Ollama API

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/ssl:/etc/caddy/ssl:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ollama-network
    depends_on:
      - ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 30G  # RAM-Limit
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - ollama-network  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=changeme_to_random_string
      - WEBUI_NAME=Ollama WebUI
    depends_on:
      - ollama
    networks:
      - ollama-network

volumes:
  open-webui-data:
  ollama:
  caddy_data:
  caddy_config:
  
networks:
  ollama-network:
    driver: bridge
