services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"   # Ollama API

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/ssl:/etc/caddy/ssl:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ai-network
    depends_on:
      - vllm
#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    restart: unless-stopped
#    ports:
#      - "11434"
#    volumes:
#      - ollama:/root/.ollama
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
#        limits:
#          memory: 30G  # RAM-Limit
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
#    networks:
#      - ai-network
#  open-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: open-webui
#    restart: unless-stopped
#    ports:
#      - "80:8080"
#    volumes:
#      - open-webui-data:/app/backend/data
#    environment:
#      - OLLAMA_BASE_URL=http://ollama:11434
#      - WEBUI_SECRET_KEY=changeme_to_random_string
#      - WEBUI_NAME=Ollama WebUI
#    depends_on:
#      - ollama
#    networks:
#      - ollama-network
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - HUGGING_FACE_HUB_TOKEN=
#      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      - PYTORCH_ALLOC_CONF=expandable_segments:True
      # Cache-Pfade explizit
      - HF_HOME=/root/.cache/huggingface
      - HUGGINGFACE_HUB_CACHE=/root/.cache/huggingface/hub
#  --model Qwen/Qwen2.5-Coder-7B-Instruct
#  --model  DragonLLM/Llama-Open-Finance-8B
    command: >
      --model openai/gpt-oss-120b
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 4
      --gpu-memory-utilization 0.80
      --max-model-len 12000
      --enable-auto-tool-choice
      --tool-call-parser llama3_json
      --enforce-eager
      --max-num-seqs 8
    volumes:
      - vllm:/root/.cache/huggingface
      - vllm_cache:/root/.cache/vllm
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped

#  openwebui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: openwebui
#    ports:
#      - "80:8080"
#    environment:
#      - OPENAI_API_BASE_URL=http://vllm:8000/v1
#      - OPENAI_API_KEY=dummy-key
#      - WEBUI_AUTH=false
#    volumes:
#      - openwebui-data:/app/backend/data
#    networks:
#      - ai-network
#    restart: unless-stopped
#    depends_on:
#      - vllm
volumes:
  openwebui-data:
  caddy_data:
  caddy_config:
  vllm:
  vllm_cache:
networks:
  ai-network:
    driver: bridge
